# -----------------------------------------------------
# BetterBanSystem Configuration File v${project.version}
# -----------------------------------------------------
# Authors: SimonPlays15 & Blubo
# Description: This file contains the configuration for BetterBanSystem.
# -----------------------------------------------------
chat:
  prefix: "&6[&cBetterBanSystem&6]"
  usePrefix: true
  language: "en_US"

database:
  # Available Types: MYSQL, SQLITE, MONGODB
  type: none

# SQLite example:
#database:
#  type: SQLITE
#  dbFile: "path/to/your/database_file.db"
# MySQL & MongoDB example:
#database:
#  type: MYSQL | MONGODB
#  hostname: 127.0.0.1
#  port: 3363
#  user: username
#  password: yoursupersecretpassword
#  database: datbase_name

automod:
  use: true
  modules:
    chat:
      spamming:
        maxMessages: 5
        action: "WARN;DELETE"
      duplicatedText:
        use: false
        action: "DELETE;MUTE!5min"
      capslock:
        use: true
        action: WARN
      links:
        use: true
        action: WARN
      phishingLinks:
        use: true
        action: INSTANTBAN
      badwords:
        use: true
        badWordList: [ ]
        action: WARN
warns:
  autodelete:
    use: true
    time: 60
    unit: MINUTES
  actions:
    - "3:MUTE:5min"


# The Permissionssystem the plugin should use to check for a players permissions
# NOTE: Spigot & BungeeCord does not support offline user checks for permissions!
permissions:
  # Available Types: SPIGOT, LUCKPERMS, BUNGEECORD, CLOUDNET, VAULT
  system: SPIGOT

logging:
  # Should we write the logs in a seperate file?
  logfile: true
  # Do you want to see debugging messages from this plugin?
  debug: false
# Exempted players (without giving the betterbansystem.exempt.ban permission)
exempted-players: [ ]
exempted-mute-players: [ ]
exempted-warn-players: [ ]
exempted-ips: [ ]

mute:
  blocked-commands:
    - me
    - tell
    - msg