name: ${project.artifactId}
authors: [ SimonPlays15, Blubo ]
version: ${project.version}
main: ${project.groupId}.BetterBanSystem
description: It got never easier to ban a user
commands:
  ban:
    description: Bans a specific player
    permission: betterbansystem.commands.ban
    usage: "/<command> [player] [reason]"